[project]
name = "map-of-post-rock"
version = "0.1.0"
description = "A project to map post-rock artists"
requires-python = ">=3.8"
dependencies = ["requests>=2.31.0"]

[tool.uv]
index-url = "http://mirrors.aliyun.com/pypi/simple"